abbr -a -- gl glab

abbr -a -- glc 'glab ci'
abbr -a -- glcc 'glab ci cancel'
abbr -a -- glccj 'glab ci cancel job'
abbr -a -- glccp 'glab ci cancel pipeline'
abbr -a -- glcl 'glab ci list'
abbr -a -- glcL 'glab ci lint'
abbr -a -- glcr 'glab ci run'
abbr -a -- glcrm 'glab ci run -b main'
abbr -a -- glcR 'glab ci retry'
abbr -a -- glcRp 'glab ci retry -p'
abbr -a -- glcs 'glab ci status'
abbr -a -- glct 'glab ci trace'
abbr -a -- glctp 'glab ci trace -p'
abbr -a -- glcT 'glab ci trigger'
abbr -a -- glcTp 'glab ci trigger -p'
abbr -a -- glcv 'glab ci view'

abbr -a -- glm 'glab mr'
abbr -a -- glmC 'glab mr close'
abbr -a -- glmc 'glab mr create'
abbr -a -- glmd 'glab mr diff'
abbr -a -- glml 'glab mr list'
abbr -a -- glmm 'glab mr merge'
abbr -a -- glmmdsy 'glab mr merge -dsy'
abbr -a -- glmr 'glab mr rebase'
abbr -a -- glmu 'glab mr update'
abbr -a -- glmur 'glab mr update --ready'
abbr -a -- glmut 'glab mr update --title'
abbr -a -- glmv 'glab mr view'

abbr -a -- glr 'glab release'
abbr -a -- glrc 'glab release create'
abbr -a -- glrd 'glab release delete'
abbr -a -- glrdw 'glab release download'
abbr -a -- glrl 'glab release list'
abbr -a -- glru 'glab release upload'
abbr -a -- glrv 'glab release view'

abbr -a -- glv 'glab variable'
abbr -a -- glvd 'glab variable delete'
abbr -a -- glvds 'glab variable delete --scope'
abbr -a -- glvg 'glab variable get'
abbr -a -- glvgs 'glab variable get --scope'
abbr -a -- glvl 'glab variable list'
abbr -a -- glvs 'glab variable set'
abbr -a -- glvss 'glab variable set --scope'
abbr -a -- glvu 'glab variable update'
abbr -a -- glvus 'glab variable update --scope'

