abbr -a -- gl glab

abbr -a -- glc 'glab ci'
abbr -a -- glca 'glab ci artifact'
abbr -a -- glcc 'glab ci cancel'
abbr -a -- glccj 'glab ci cancel job'
abbr -a -- glccp 'glab ci cancel pipeline'
abbr -a -- glcd 'glab ci delete'
abbr -a -- glcf 'glab ci config'
abbr -a -- glcl 'glab ci list'
abbr -a -- glcL 'glab ci lint'
abbr -a -- glcr 'glab ci run'
abbr -a -- glcrm 'glab ci run -b main'
abbr -a -- glcR 'glab ci retry'
abbr -a -- glcRp 'glab ci retry -p'
abbr -a -- glcs 'glab ci status'
abbr -a -- glcsl 'glab ci status --live'
abbr -a -- glct 'glab ci trace'
abbr -a -- glctp 'glab ci trace -p'
abbr -a -- glcT 'glab ci trigger'
abbr -a -- glcTp 'glab ci trigger -p'
abbr -a -- glcv 'glab ci view'

abbr -a -- glm 'glab mr'
abbr -a -- glmA 'glab mr revoke'
abbr -a -- glmC 'glab mr close'
abbr -a -- glma 'glab mr approve'
abbr -a -- glmc 'glab mr create'
abbr -a -- glmco 'glab mr checkout'
abbr -a -- glmd 'glab mr diff'
abbr -a -- glml 'glab mr list'
abbr -a -- glmm 'glab mr merge'
abbr -a -- glmmdsy 'glab mr merge -dsy'
abbr -a -- glmn 'glab mr note'
abbr -a -- glmR 'glab mr reopen'
abbr -a -- glmr 'glab mr rebase'
abbr -a -- glms 'glab mr subscribe'
abbr -a -- glmt 'glab mr todo'
abbr -a -- glmu 'glab mr update'
abbr -a -- glmur 'glab mr update --ready'
abbr -a -- glmut 'glab mr update --title'
abbr -a -- glmv 'glab mr view'

abbr -a -- gli 'glab issue'
abbr -a -- gliC 'glab issue close'
abbr -a -- glic 'glab issue create'
abbr -a -- glil 'glab issue list'
abbr -a -- gliu 'glab issue update'
abbr -a -- gliv 'glab issue view'

abbr -a -- gla 'glab auth'
abbr -a -- glaL 'glab auth logout'
abbr -a -- glal 'glab auth login'
abbr -a -- glas 'glab auth status'

abbr -a -- glp 'glab repo'
abbr -a -- glpc 'glab repo clone'
abbr -a -- glpf 'glab repo fork'
abbr -a -- glpv 'glab repo view'

abbr -a -- glr 'glab release'
abbr -a -- glrc 'glab release create'
abbr -a -- glrd 'glab release delete'
abbr -a -- glrdw 'glab release download'
abbr -a -- glrl 'glab release list'
abbr -a -- glru 'glab release upload'
abbr -a -- glrv 'glab release view'

abbr -a -- gls 'glab schedule'
abbr -a -- glsc 'glab schedule create'
abbr -a -- glsl 'glab schedule list'
abbr -a -- glsr 'glab schedule run'
abbr -a -- glsv 'glab schedule view'

abbr -a -- glv 'glab variable'
abbr -a -- glvd 'glab variable delete'
abbr -a -- glvds 'glab variable delete --scope'
abbr -a -- glvg 'glab variable get'
abbr -a -- glvgs 'glab variable get --scope'
abbr -a -- glvl 'glab variable list'
abbr -a -- glvs 'glab variable set'
abbr -a -- glvss 'glab variable set --scope'
abbr -a -- glvu 'glab variable update'
abbr -a -- glvus 'glab variable update --scope'
